// Copyright (c) 2012 National Instruments.
// All rights reserved.
// License: NATIONAL INSTRUMENTS SOFTWARE LICENSE AGREEMENT
//   Refer to "MHDDK License Agreement.pdf" in the root of this distribution.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This file is autogenerated!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#ifndef ___tDioPortsValues_h___
#define ___tDioPortsValues_h___

namespace nDioPorts {
   typedef enum {
      kNo_Filter                         = 0,
      kSmall_Filter                      = 1,
      kMedium_Filter                     = 2,
      kLarge_Filter                      = 3,
   } tDI_Filter_Select_t;

   typedef enum {
      kWDT_Disabled                      = 0,
      kWDT_Freeze                        = 1,
      kWDT_Tristate                      = 2,
      kWDT_SafeValue                     = 3,
   } tDO_WDT_Mode_t;

   namespace nDI_ChangeIrqRE_Register {
      namespace nDI_ChangeIrqRE_Port0 {
         enum {
            kMask = 0xff,
            kOffset = 0,
         };
      }

      namespace nDI_ChangeIrqRE_Port1 {
         enum {
            kMask = 0xff00,
            kOffset = 0x8,
         };
      }

      namespace nDI_ChangeIrqRE_Port2 {
         enum {
            kMask = 0xff0000,
            kOffset = 0x10,
         };
      }

      namespace nDI_ChangeIrqRE_Port3 {
         enum {
            kMask = 0xff000000,
            kOffset = 0x18,
         };
      }

   }

   namespace nDI_ChangeDetectLatched_Register {
      namespace nDI_ChangeDetectLatched_Port0 {
         enum {
            kMask = 0xff,
            kOffset = 0,
         };
      }

      namespace nDI_ChangeDetectLatched_Port1 {
         enum {
            kMask = 0xff00,
            kOffset = 0x8,
         };
      }

      namespace nDI_ChangeDetectLatched_Port2 {
         enum {
            kMask = 0xff0000,
            kOffset = 0x10,
         };
      }

      namespace nDI_ChangeDetectLatched_Port3 {
         enum {
            kMask = 0xff000000,
            kOffset = 0x18,
         };
      }

   }

   namespace nDI_ChangeIrqFE_Register {
      namespace nDI_ChangeIrqFE_Port0 {
         enum {
            kMask = 0xff,
            kOffset = 0,
         };
      }

      namespace nDI_ChangeIrqFE_Port1 {
         enum {
            kMask = 0xff00,
            kOffset = 0x8,
         };
      }

      namespace nDI_ChangeIrqFE_Port2 {
         enum {
            kMask = 0xff0000,
            kOffset = 0x10,
         };
      }

      namespace nDI_ChangeIrqFE_Port3 {
         enum {
            kMask = 0xff000000,
            kOffset = 0x18,
         };
      }

   }

   namespace nStatic_Digital_Input_Register {
      namespace nDIO_StaticInputValue_Port0 {
         enum {
            kMask = 0xff,
            kOffset = 0,
         };
      }

      namespace nDIO_StaticInputValue_Port1 {
         enum {
            kMask = 0xff00,
            kOffset = 0x8,
         };
      }

      namespace nDIO_StaticInputValue_Port2 {
         enum {
            kMask = 0xff0000,
            kOffset = 0x10,
         };
      }

      namespace nDIO_StaticInputValue_Port3 {
         enum {
            kMask = 0xff000000,
            kOffset = 0x18,
         };
      }

   }

   namespace nStatic_Digital_Output_Register {
      namespace nDIO_StaticOutputValue_Port0 {
         enum {
            kMask = 0xff,
            kOffset = 0,
         };
      }

      namespace nDIO_StaticOutputValue_Port1 {
         enum {
            kMask = 0xff00,
            kOffset = 0x8,
         };
      }

      namespace nDIO_StaticOutputValue_Port2 {
         enum {
            kMask = 0xff0000,
            kOffset = 0x10,
         };
      }

      namespace nDIO_StaticOutputValue_Port3 {
         enum {
            kMask = 0xff000000,
            kOffset = 0x18,
         };
      }

   }

   namespace nDIO_Direction_Register {
      namespace nDIODirection_Port0 {
         enum {
            kMask = 0xff,
            kOffset = 0,
         };
      }

      namespace nDIODirection_Port1 {
         enum {
            kMask = 0xff00,
            kOffset = 0x8,
         };
      }

      namespace nDIODirection_Port2 {
         enum {
            kMask = 0xff0000,
            kOffset = 0x10,
         };
      }

      namespace nDIODirection_Port3 {
         enum {
            kMask = 0xff000000,
            kOffset = 0x18,
         };
      }

   }

   namespace nDI_FilterRegister_Port0and1 {
      namespace nDI_Filter_Select_Port0_Line0 {
         enum {
            kMask = 0x3,
            kOffset = 0,
         };
      }

      namespace nDI_Filter_Select_Port0_Line1 {
         enum {
            kMask = 0xc,
            kOffset = 0x2,
         };
      }

      namespace nDI_Filter_Select_Port0_Line2 {
         enum {
            kMask = 0x30,
            kOffset = 0x4,
         };
      }

      namespace nDI_Filter_Select_Port0_Line3 {
         enum {
            kMask = 0xc0,
            kOffset = 0x6,
         };
      }

      namespace nDI_Filter_Select_Port0_Line4 {
         enum {
            kMask = 0x300,
            kOffset = 0x8,
         };
      }

      namespace nDI_Filter_Select_Port0_Line5 {
         enum {
            kMask = 0xc00,
            kOffset = 0xa,
         };
      }

      namespace nDI_Filter_Select_Port0_Line6 {
         enum {
            kMask = 0x3000,
            kOffset = 0xc,
         };
      }

      namespace nDI_Filter_Select_Port0_Line7 {
         enum {
            kMask = 0xc000,
            kOffset = 0xe,
         };
      }

      namespace nDI_Filter_Select_Port1_Line0 {
         enum {
            kMask = 0x30000,
            kOffset = 0x10,
         };
      }

      namespace nDI_Filter_Select_Port1_Line1 {
         enum {
            kMask = 0xc0000,
            kOffset = 0x12,
         };
      }

      namespace nDI_Filter_Select_Port1_Line2 {
         enum {
            kMask = 0x300000,
            kOffset = 0x14,
         };
      }

      namespace nDI_Filter_Select_Port1_Line3 {
         enum {
            kMask = 0xc00000,
            kOffset = 0x16,
         };
      }

      namespace nDI_Filter_Select_Port1_Line4 {
         enum {
            kMask = 0x3000000,
            kOffset = 0x18,
         };
      }

      namespace nDI_Filter_Select_Port1_Line5 {
         enum {
            kMask = 0xc000000,
            kOffset = 0x1a,
         };
      }

      namespace nDI_Filter_Select_Port1_Line6 {
         enum {
            kMask = 0x30000000,
            kOffset = 0x1c,
         };
      }

      namespace nDI_Filter_Select_Port1_Line7 {
         enum {
            kMask = 0xc0000000,
            kOffset = 0x1e,
         };
      }

   }

   namespace nDI_FilterRegister_Port2and3 {
      namespace nDI_Filter_Select_Port2_Line0 {
         enum {
            kMask = 0x3,
            kOffset = 0,
         };
      }

      namespace nDI_Filter_Select_Port2_Line1 {
         enum {
            kMask = 0xc,
            kOffset = 0x2,
         };
      }

      namespace nDI_Filter_Select_Port2_Line2 {
         enum {
            kMask = 0x30,
            kOffset = 0x4,
         };
      }

      namespace nDI_Filter_Select_Port2_Line3 {
         enum {
            kMask = 0xc0,
            kOffset = 0x6,
         };
      }

      namespace nDI_Filter_Select_Port2_Line4 {
         enum {
            kMask = 0x300,
            kOffset = 0x8,
         };
      }

      namespace nDI_Filter_Select_Port2_Line5 {
         enum {
            kMask = 0xc00,
            kOffset = 0xa,
         };
      }

      namespace nDI_Filter_Select_Port2_Line6 {
         enum {
            kMask = 0x3000,
            kOffset = 0xc,
         };
      }

      namespace nDI_Filter_Select_Port2_Line7 {
         enum {
            kMask = 0xc000,
            kOffset = 0xe,
         };
      }

      namespace nDI_Filter_Select_Port3_Line0 {
         enum {
            kMask = 0x30000,
            kOffset = 0x10,
         };
      }

      namespace nDI_Filter_Select_Port3_Line1 {
         enum {
            kMask = 0xc0000,
            kOffset = 0x12,
         };
      }

      namespace nDI_Filter_Select_Port3_Line2 {
         enum {
            kMask = 0x300000,
            kOffset = 0x14,
         };
      }

      namespace nDI_Filter_Select_Port3_Line3 {
         enum {
            kMask = 0xc00000,
            kOffset = 0x16,
         };
      }

      namespace nDI_Filter_Select_Port3_Line4 {
         enum {
            kMask = 0x3000000,
            kOffset = 0x18,
         };
      }

      namespace nDI_Filter_Select_Port3_Line5 {
         enum {
            kMask = 0xc000000,
            kOffset = 0x1a,
         };
      }

      namespace nDI_Filter_Select_Port3_Line6 {
         enum {
            kMask = 0x30000000,
            kOffset = 0x1c,
         };
      }

      namespace nDI_Filter_Select_Port3_Line7 {
         enum {
            kMask = 0xc0000000,
            kOffset = 0x1e,
         };
      }

   }

   namespace nDO_WDT_SafeStateRegister {
      namespace nDO_WDT_SafeStateValue_Port0 {
         enum {
            kMask = 0xff,
            kOffset = 0,
         };
      }

      namespace nDO_WDT_SafeStateValue_Port1 {
         enum {
            kMask = 0xff00,
            kOffset = 0x8,
         };
      }

      namespace nDO_WDT_SafeStateValue_Port2 {
         enum {
            kMask = 0xff0000,
            kOffset = 0x10,
         };
      }

      namespace nDO_WDT_SafeStateValue_Port3 {
         enum {
            kMask = 0xff000000,
            kOffset = 0x18,
         };
      }

   }

   namespace nDO_WDT_ModeSelect_Port0and1_Register {
      namespace nDO_WDT_ModePort0_Line0 {
         enum {
            kMask = 0x3,
            kOffset = 0,
         };
      }

      namespace nDO_WDT_ModePort0_Line1 {
         enum {
            kMask = 0xc,
            kOffset = 0x2,
         };
      }

      namespace nDO_WDT_ModePort0_Line2 {
         enum {
            kMask = 0x30,
            kOffset = 0x4,
         };
      }

      namespace nDO_WDT_ModePort0_Line3 {
         enum {
            kMask = 0xc0,
            kOffset = 0x6,
         };
      }

      namespace nDO_WDT_ModePort0_Line4 {
         enum {
            kMask = 0x300,
            kOffset = 0x8,
         };
      }

      namespace nDO_WDT_ModePort0_Line5 {
         enum {
            kMask = 0xc00,
            kOffset = 0xa,
         };
      }

      namespace nDO_WDT_ModePort0_Line6 {
         enum {
            kMask = 0x3000,
            kOffset = 0xc,
         };
      }

      namespace nDO_WDT_ModePort0_Line7 {
         enum {
            kMask = 0xc000,
            kOffset = 0xe,
         };
      }

      namespace nDO_WDT_ModePort1_Line0 {
         enum {
            kMask = 0x30000,
            kOffset = 0x10,
         };
      }

      namespace nDO_WDT_ModePort1_Line1 {
         enum {
            kMask = 0xc0000,
            kOffset = 0x12,
         };
      }

      namespace nDO_WDT_ModePort1_Line2 {
         enum {
            kMask = 0x300000,
            kOffset = 0x14,
         };
      }

      namespace nDO_WDT_ModePort1_Line3 {
         enum {
            kMask = 0xc00000,
            kOffset = 0x16,
         };
      }

      namespace nDO_WDT_ModePort1_Line4 {
         enum {
            kMask = 0x3000000,
            kOffset = 0x18,
         };
      }

      namespace nDO_WDT_ModePort1_Line5 {
         enum {
            kMask = 0xc000000,
            kOffset = 0x1a,
         };
      }

      namespace nDO_WDT_ModePort1_Line6 {
         enum {
            kMask = 0x30000000,
            kOffset = 0x1c,
         };
      }

      namespace nDO_WDT_ModePort1_Line7 {
         enum {
            kMask = 0xc0000000,
            kOffset = 0x1e,
         };
      }

   }

   namespace nDO_WDT_ModeSelect_Port2and3_Register {
      namespace nDO_WDT_ModePort2_Line0 {
         enum {
            kMask = 0x3,
            kOffset = 0,
         };
      }

      namespace nDO_WDT_ModePort2_Line1 {
         enum {
            kMask = 0xc,
            kOffset = 0x2,
         };
      }

      namespace nDO_WDT_ModePort2_Line2 {
         enum {
            kMask = 0x30,
            kOffset = 0x4,
         };
      }

      namespace nDO_WDT_ModePort2_Line3 {
         enum {
            kMask = 0xc0,
            kOffset = 0x6,
         };
      }

      namespace nDO_WDT_ModePort2_Line4 {
         enum {
            kMask = 0x300,
            kOffset = 0x8,
         };
      }

      namespace nDO_WDT_ModePort2_Line5 {
         enum {
            kMask = 0xc00,
            kOffset = 0xa,
         };
      }

      namespace nDO_WDT_ModePort2_Line6 {
         enum {
            kMask = 0x3000,
            kOffset = 0xc,
         };
      }

      namespace nDO_WDT_ModePort2_Line7 {
         enum {
            kMask = 0xc000,
            kOffset = 0xe,
         };
      }

      namespace nDO_WDT_ModePort3_Line0 {
         enum {
            kMask = 0x30000,
            kOffset = 0x10,
         };
      }

      namespace nDO_WDT_ModePort3_Line1 {
         enum {
            kMask = 0xc0000,
            kOffset = 0x12,
         };
      }

      namespace nDO_WDT_ModePort3_Line2 {
         enum {
            kMask = 0x300000,
            kOffset = 0x14,
         };
      }

      namespace nDO_WDT_ModePort3_Line3 {
         enum {
            kMask = 0xc00000,
            kOffset = 0x16,
         };
      }

      namespace nDO_WDT_ModePort3_Line4 {
         enum {
            kMask = 0x3000000,
            kOffset = 0x18,
         };
      }

      namespace nDO_WDT_ModePort3_Line5 {
         enum {
            kMask = 0xc000000,
            kOffset = 0x1a,
         };
      }

      namespace nDO_WDT_ModePort3_Line6 {
         enum {
            kMask = 0x30000000,
            kOffset = 0x1c,
         };
      }

      namespace nDO_WDT_ModePort3_Line7 {
         enum {
            kMask = 0xc0000000,
            kOffset = 0x1e,
         };
      }

   }

   using namespace nDI_ChangeIrqRE_Register;
   using namespace nDI_ChangeDetectLatched_Register;
   using namespace nDI_ChangeIrqFE_Register;
   using namespace nStatic_Digital_Input_Register;
   using namespace nStatic_Digital_Output_Register;
   using namespace nDIO_Direction_Register;
   using namespace nDI_FilterRegister_Port0and1;
   using namespace nDI_FilterRegister_Port2and3;
   using namespace nDO_WDT_SafeStateRegister;
   using namespace nDO_WDT_ModeSelect_Port0and1_Register;
   using namespace nDO_WDT_ModeSelect_Port2and3_Register;
}

#endif


// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This file is autogenerated!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

