// Copyright (c) 2012 National Instruments.
// All rights reserved.
// License: NATIONAL INSTRUMENTS SOFTWARE LICENSE AGREEMENT
//   Refer to "MHDDK License Agreement.pdf" in the root of this distribution.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This file is autogenerated!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#ifndef ___tPCIe6509Values_h___
#define ___tPCIe6509Values_h___

#include "tStaticDioValues.h"
#include "tChpServicesValues.h"
#include "tCHInChValues.h"

namespace nPCIe6509 {
   using namespace nStaticDio;
   using namespace nChpServices;
   using namespace nChpServices;
   using namespace nCHInCh;
}

#endif


// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This file is autogenerated!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

