// Copyright (c) 2012 National Instruments.
// All rights reserved.
// License: NATIONAL INSTRUMENTS SOFTWARE LICENSE AGREEMENT
//   Refer to "MHDDK License Agreement.pdf" in the root of this distribution.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This file is autogenerated!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#ifndef ___tStaticDio_h___
#define ___tStaticDio_h___

// includes
#include "osiTypes.h"
#include "osiBus.h"
#include "tDioPorts.h"
#include "tPfiPorts.h"


#ifndef ___tStaticDioValues_h___
#include "tStaticDioValues.h"
#endif

class tStaticDio
{
public:
   tDioPorts DioPortsLo;
   tDioPorts DioPortsHi;
   tPfiPorts PfiPortsLo;
   tPfiPorts PfiPortsHi;

   //---------------------------------------------------------------------------
   // IO Strategies
   //---------------------------------------------------------------------------
   //---------------------------------------------------------------------------
   // Register Groups
   //---------------------------------------------------------------------------

   //----------------------------------------
   // Register/Field Ids
   //----------------------------------------
   typedef enum {

      kMaxRegisterId = -1

   } tId;

   tStaticDio(tBusSpaceReference addrSpace, nMDBG::tStatus2* statusChain = NULL);
   tStaticDio();
   void initialize(tBusSpaceReference addrSpace, u32 addressOffset, nMDBG::tStatus2* statusChain = NULL);
   void reset(nMDBG::tStatus2* statusChain = NULL);
   virtual ~tStaticDio();

   inline tBusSpaceReference getBusSpaceReference(void) const;

   inline void setAddressOffset(u32 value, nMDBG::tStatus2* statusChain = NULL);
   inline u32  getAddressOffset(nMDBG::tStatus2* statusChain = NULL);
private:
   void _initialize(nMDBG::tStatus2* statusChain = NULL);
   tBusSpaceReference _addrSpace;
   u32 _addressOffset;

};

#ifndef ___tStaticDio_ipp___
#ifndef ___tStaticDio_h_no_inline___
#include "tStaticDio.ipp"
#endif

#endif

#endif


// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This file is autogenerated!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

