// Copyright (c) 2012 National Instruments.
// All rights reserved.
// License: NATIONAL INSTRUMENTS SOFTWARE LICENSE AGREEMENT
//   Refer to "MHDDK License Agreement.pdf" in the root of this distribution.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This file is autogenerated!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#ifndef ___tStaticDio_h___
#include "tStaticDio.h"
#endif

tStaticDio::tStaticDio(tBusSpaceReference addrSpace, nMDBG::tStatus2* s)
 : DioPortsLo()
,
   DioPortsHi()
,
   PfiPortsLo()
,
   PfiPortsHi()

{
   _addressOffset = 0;
   _addrSpace = addrSpace;

   _initialize(s);
}

tStaticDio::tStaticDio()
 : DioPortsLo()
,
   DioPortsHi()
,
   PfiPortsLo()
,
   PfiPortsHi()

{
   _addressOffset = 0;

}

void tStaticDio::initialize(tBusSpaceReference addrSpace, u32 addressOffset, nMDBG::tStatus2* s)
{

   _addrSpace = addrSpace;
   _addressOffset = addressOffset;

   _initialize(s);
}

void tStaticDio::reset(nMDBG::tStatus2* s)
{
   if (s && s->isFatal()) return;

}

void tStaticDio::_initialize(nMDBG::tStatus2* s)
{
   if (s && s->isFatal()) return;

   DioPortsLo.initialize(_addrSpace, 0x20000 + getAddressOffset(s), s);
   DioPortsHi.initialize(_addrSpace, 0x40000 + getAddressOffset(s), s);
   PfiPortsLo.initialize(_addrSpace, 0x20000 + getAddressOffset(s), s);
   PfiPortsHi.initialize(_addrSpace, 0x40000 + getAddressOffset(s), s);



   //----------------------------------------
   // set register maps of all registers
   //----------------------------------------

   //----------------------------------------
   // reset registers
   //----------------------------------------
   reset(s);
}

tStaticDio::~tStaticDio()
{
}



// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This file is autogenerated!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

