// Copyright (c) 2012 National Instruments.
// All rights reserved.
// License: NATIONAL INSTRUMENTS SOFTWARE LICENSE AGREEMENT
//   Refer to "MHDDK License Agreement.pdf" in the root of this distribution.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This file is autogenerated!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#ifndef ___tStaticDioValues_h___
#define ___tStaticDioValues_h___

#include "tDioPortsValues.h"
#include "tPfiPortsValues.h"

namespace nStaticDio {
   using namespace nDioPorts;
   using namespace nDioPorts;
   using namespace nPfiPorts;
   using namespace nPfiPorts;
}

#endif


// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This file is autogenerated!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

